Implemented class mapping
atk4/dsql pull request #182
Opened 2020-04-09 16:25 UTC by nitricware

Hello,

I implemented `PDO::FETCH_CLASS` in a non-breaking, optional way

Compare with Example #4: https://www.php.net/manual/de/pdostatement.fetchall.php

This effects `get()`, `getOne()` and `getRow()` in `Expression.php`.

Maybe it's of use?

Thanks, Kurt

2020-04-09 18:58 UTC, mvorisek requested changes

2020-04-09 18:58 UTC, mvorisek commented on src/Expression.php
> +    public function get(string $classname = 'stdClass', $returnObject = false)
Seems like a bad design - why two parameters if one is enought? And you should use `\stdClass::class` instead of string.

2020-04-09 19:01 UTC, mvorisek commented
What is the real use case? Makes this even sense with dsql? (user can always use `execute()` + anything he need)

2020-04-10 04:48 UTC, nitricware commented
Use case was comfort.

However, as you pointed out

```php
$e = $q->execute();
$r = $e->fetchAll(\PDO::FETCH_CLASS, SomeClass::class);
```

does the job just fine.

> why two parameters if one is enought? [sic!]

`$returnObject = false` is for compatibility reasons only. The tests would fail because at some point, an `array` is expected and an `object` is returned.

Since this pull request can be worked around with just one line of extra code, I'll close the pull request. Thanks for considering! :)

2020-04-10 04:48 UTC, closed without merging